replicaCount: 1
app:
  name: tf-serving-model
namespace: default
image:
  name: tf-serving-model-minimal
  tag: latest
  owner: <dockerhub-username>
  pullPolicy: IfNotPresent
container:
  name: tf-serving-model-container
service:
  type: ClusterIP
  port: 8501
  targetPort: 8501
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
