replicaCount: 1
app:
  name: celsiusify
namespace: default
image:
  name: celsiusify
  tag: latest
  owner: krzysiek77
  pullPolicy: IfNotPresent
container:
  name: celsiusify-container
service:
  type: ClusterIP
  port: 8080
  targetPort: 80
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
